kind = "web"
previewPath = "/"
title = "MediNova"
version = "1.0.0"
id = "artifacts/medinova"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 25403

[services.development]
run = "pnpm --filter @workspace/medinova run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/medinova", "run", "build" ]
publicDir = "artifacts/medinova/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "25403"
BASE_PATH = "/"
